#!/usr/bin/env python3
"""Render the owned-tap formula from verified native release inputs, without publishing."""
import argparse
import json
from pathlib import Path
import re
import tempfile
from native_artifacts import TARGETS, binary_names, digest, inspect_binary, read_checked, unpack_checked

REPOSITORY = 'https://github.com/hashimkarim/usagestat'


def render(version, manifests, *, local_directory=None, formula_name='usagestat'):
    stable = r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
    identifier = r'(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)'
    allowed = stable + (rf'(?:-{identifier}(?:\.{identifier})*)?' if local_directory else '')
    if not re.fullmatch(allowed, version):
        raise ValueError('Homebrew requires a stable semantic version, or a valid prerelease in a local rehearsal')
    if not re.fullmatch(r'usagestat(?:-fixture-[a-z0-9]+)?', formula_name):
        raise ValueError('Unexpected Homebrew formula name')
    selected = {}
    for manifest in manifests:
        target = manifest['target']
        if target not in TARGETS or manifest['os'] not in ('linux', 'darwin'):
            raise ValueError('Unexpected Homebrew target')
        metadata = TARGETS[target]
        if (manifest['os'], manifest['arch']) != (metadata['os'], metadata['arch']):
            raise ValueError('Homebrew target metadata mismatch')
        if manifest['version'] != version or manifest['sourceDirty']:
            raise ValueError('Homebrew input version/clean-source mismatch')
        if not local_directory and not manifest['minimumSystemQualified']:
            raise ValueError('Unqualified native target cannot enter the stable formula')
        name = metadata['asset'] + '.tar.gz'
        if manifest['archive']['name'] != name or not re.fullmatch('[a-f0-9]{64}', manifest['archive']['sha256']):
            raise ValueError('Unexpected Homebrew archive name or checksum')
        key = (metadata['os'], metadata['arch'])
        if key in selected:
            raise ValueError('Duplicate Homebrew target')
        selected[key] = manifest
    if not selected:
        raise ValueError('No Homebrew targets')
    for os_name in ('linux', 'darwin'):
        if any(key[0] == os_name for key in selected) and not all((os_name, arch) in selected for arch in ('arm64', 'x64')):
            raise ValueError('Homebrew platform requires both architecture inputs')
    for field in ('sourceCommit', 'resourcesSha256'):
        if len({m[field] for m in selected.values()}) != 1:
            raise ValueError('Homebrew archives disagree on ' + field)
    klass = ''.join(part.capitalize() for part in formula_name.split('-'))
    lines = ['# Generated by tools/publish/scripts/homebrew_formula.py.',
             '# Local unsigned rehearsal only.' if local_directory else '# Verified stable release inputs only.',
             f'class {klass} < Formula', '  desc "Scriptable CLI for local agent usage data"',
             f'  homepage "{REPOSITORY}"', f'  version "{version}"', '  license "MIT"']
    if not any(key[0] == 'darwin' for key in selected):
        lines.append('  depends_on :linux')
    elif not any(key[0] == 'linux' for key in selected):
        lines.append('  depends_on :macos')
    for os_name, stanza in [('linux', 'on_linux'), ('darwin', 'on_macos')]:
        if (os_name, 'arm64') not in selected:
            continue
        lines += ['', f'  {stanza} do']
        if os_name == 'darwin':
            lines.append('    depends_on macos: :big_sur')
        lines.append('    if Hardware::CPU.arm?')
        for index, arch in enumerate(('arm64', 'x64')):
            manifest = selected[(os_name, arch)]
            name = manifest['archive']['name']
            url = (local_directory.resolve() / name).as_uri() if local_directory else f'{REPOSITORY}/releases/download/v{version}/{name}'
            if index:
                lines.append('    else')
            lines += ['      url ' + json.dumps(url), '      sha256 ' + json.dumps(manifest['archive']['sha256'])]
        lines += ['    end', '  end']
    lines += ['', '  def install', '    bin.install "usagestat", "usagestatd"',
              '    (share/"usagestat").install "plugins", "LICENSE"', '  end', '',
              '  def caveats', '    <<~EOS',
              '      Enable login startup explicitly with: usagestat daemon enable',
              '      The usagestat CLI owns startup registration; no brew services entry is installed.',
              '      Before removing a managed installation, run: usagestat daemon unregister',
              '      Configuration, history, and credentials are retained when uninstalling.',
              '    EOS', '  end', '', '  test do',
              '    assert_match version.to_s, shell_output("#{bin}/usagestat --version")',
              '    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")',
              '    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s',
              '    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s',
              '    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))',
              '    assert providers.any? { |provider| provider["id"] == "codex" }',
              '    assert_path_exists share/"usagestat/plugins/codex/plugin.json"',
              '  end', 'end', '']
    return '\n'.join(lines)


def generate(directory, *, rehearsal=False, formula_name='usagestat'):
    complete = json.loads(read_checked(directory / 'usagestat-artifacts.json'))
    if complete['schemaVersion'] != 1:
        raise ValueError('Unknown release input schema')
    manifests = [m for m in complete['targets'] if m['os'] in ('linux', 'darwin')
                 and (rehearsal or m['minimumSystemQualified'])]
    formula = render(complete['version'], manifests,
                     local_directory=directory if rehearsal else None, formula_name=formula_name)
    with tempfile.TemporaryDirectory(prefix='usagestat formula validation ') as temporary:
        for manifest in manifests:
            if manifest['sourceCommit'] != complete['sourceCommit']:
                raise ValueError('Homebrew source commit differs from release')
            target = manifest['target']
            recorded = json.loads(read_checked(directory / (TARGETS[target]['asset'] + '.manifest.json')))
            if recorded != manifest:
                raise ValueError('Homebrew aggregate differs from target manifest')
            root = Path(temporary) / target
            unpack_checked(manifest, directory / manifest['archive']['name'], root)
            for binary in binary_names(target):
                inspect_binary((root / binary).read_bytes(), target)
            resources = {item['path']: digest((root / item['path']).read_bytes()) for item in manifest['files']
                         if item['path'] not in binary_names(target)}
            if digest(json.dumps(resources, sort_keys=True).encode()) != manifest['resourcesSha256']:
                raise ValueError('Homebrew resources disagree with manifest')
    return formula


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--artifacts', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--rehearsal', action='store_true')
    args = parser.parse_args()
    result = generate(args.artifacts.resolve(), rehearsal=args.rehearsal)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open('x', encoding='utf-8') as output:
        output.write(result)
